name: A collection of services
router_dsn: ws://127.0.0.1:8080/ws
realm: realm1
apps:
    - aservice
    - bservice
# From environmental variable with default
a_user: ${A_USER:default user}
# From environmental variable with no default
a_password: ${A_PASSWORD}
logging:
    loggers:
        mu:
            handles:
                - console
            level: DEBUG
