name: A collection of services
router_dsn: ws://127.0.0.1:8080/ws
realm: realm1
apps:
    - aservice
    - bservice
a_user:
        env: A_USER
        default: "auser"
a_password:
    env: A_PASSWORD

