language: python

python:
    - '3.5'

cache:
  directories:
    - $HOME/.cache/pip

before_install:
    - pip install --upgrade pip

install:
    - pip install -e .
    - pip install -r dev_requirements.txt

script:
    - py.test --pep8 --cov mu
